/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Grupo3
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public Vista() {
        initComponents();
        this.btn_modificar_relacion.setVisible(false);
        this.btn_borrar_relacion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_participa = new javax.swing.JDialog();
        menu_participa_eti_nombre_guerra = new javax.swing.JLabel();
        menu_participa_field_id_guerra = new javax.swing.JTextField();
        menu_participa_field_id_pais = new javax.swing.JTextField();
        menu_participa_eti_nombre_pais = new javax.swing.JLabel();
        menu_participa_cbox_bando = new javax.swing.JComboBox<>();
        menu_participa_btn_aceptar = new javax.swing.JButton();
        menu_participa_btn_cancelar = new javax.swing.JButton();
        menu_participa_eti_bando = new javax.swing.JLabel();
        menu_participa_eti_fecha_salida = new javax.swing.JLabel();
        menu_participa_eti_fecha_entrada = new javax.swing.JLabel();
        menu_participa_txtfield_fecha_salida = new javax.swing.JTextField();
        menu_participa_txtfield_fecha_entrada = new javax.swing.JTextField();
        North = new javax.swing.JPanel();
        btn_participa = new javax.swing.JButton();
        btn_paises = new javax.swing.JButton();
        btn_independencia = new javax.swing.JButton();
        btn_guerras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Center = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        South = new javax.swing.JPanel();
        mensaje = new javax.swing.JLabel();
        btn_modificar_relacion = new javax.swing.JButton();
        btn_borrar_relacion = new javax.swing.JButton();
        West = new javax.swing.JPanel();
        panel_datos_guerra = new javax.swing.JPanel();
        eti_fecha_inicio = new javax.swing.JLabel();
        eti_fecha_fin = new javax.swing.JLabel();
        eti_id_guerra = new javax.swing.JLabel();
        eti_nombre_guerra = new javax.swing.JLabel();
        lista_guerras = new javax.swing.JComboBox<>();
        btn_borrar_guerra = new javax.swing.JButton();
        panel_box_paises = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_paises_neutrales = new javax.swing.JList<>();
        añadir_pais = new javax.swing.JButton();
        panel_añadir_guerra = new javax.swing.JPanel();
        eti_nombre_guerra2 = new javax.swing.JLabel();
        txtfield_nombre_guerra = new javax.swing.JTextField();
        eti_fecha_inicio2 = new javax.swing.JLabel();
        txtfield_fecha_inicio = new javax.swing.JTextField();
        txtfield_fecha_fin = new javax.swing.JTextField();
        eti_fecha_fin2 = new javax.swing.JLabel();
        btn_nueva_guerra = new javax.swing.JButton();
        East = new javax.swing.JPanel();
        panel_datos_pais = new javax.swing.JPanel();
        eti_id_pais = new javax.swing.JLabel();
        eti_nombre_pais = new javax.swing.JLabel();
        eti_periodos_independencia = new javax.swing.JLabel();
        lista_paises = new javax.swing.JComboBox<>();
        btn_borrar_pais = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lista_periodos_independencia = new javax.swing.JList<>();
        btn_borrar_periodo_independencia = new javax.swing.JButton();
        panel_box_guerras = new javax.swing.JPanel();
        añadir_guerra = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_guerras_neutral = new javax.swing.JList<>();
        panel_añadir_pais = new javax.swing.JPanel();
        eti_nombre_pais1 = new javax.swing.JLabel();
        txtfield_nombre_pais = new javax.swing.JTextField();
        btn_nuevo_pais = new javax.swing.JButton();
        txtfield_inicio_independencia = new javax.swing.JTextField();
        txtfield_fin_independencia = new javax.swing.JTextField();
        btn_nueva_independencia = new javax.swing.JButton();
        eti_periodos_independencia1 = new javax.swing.JLabel();

        menu_participa.setTitle("Añadir relación");
        menu_participa.setMinimumSize(new java.awt.Dimension(400, 300));
        menu_participa.setPreferredSize(new java.awt.Dimension(400, 300));
        menu_participa.setResizable(false);

        menu_participa_eti_nombre_guerra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu_participa_eti_nombre_guerra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_participa_eti_nombre_guerra.setText("Guerra");

        menu_participa_field_id_guerra.setEditable(false);
        menu_participa_field_id_guerra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        menu_participa_field_id_guerra.setOpaque(false);

        menu_participa_field_id_pais.setEditable(false);
        menu_participa_field_id_pais.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        menu_participa_field_id_pais.setOpaque(false);

        menu_participa_eti_nombre_pais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu_participa_eti_nombre_pais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_participa_eti_nombre_pais.setText("País");

        menu_participa_cbox_bando.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", "Vencedor", "Perdedor" }));

        menu_participa_btn_aceptar.setText("Aceptar");
        menu_participa_btn_aceptar.setActionCommand("Aceptar_Participa");

        menu_participa_btn_cancelar.setText("Cancelar");
        menu_participa_btn_cancelar.setActionCommand("Cancelar_Participa");

        menu_participa_eti_bando.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        menu_participa_eti_bando.setText("bando:");

        menu_participa_eti_fecha_salida.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        menu_participa_eti_fecha_salida.setText("fecha_salida:");

        menu_participa_eti_fecha_entrada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        menu_participa_eti_fecha_entrada.setText("fecha_entrada:");

        javax.swing.GroupLayout menu_participaLayout = new javax.swing.GroupLayout(menu_participa.getContentPane());
        menu_participa.getContentPane().setLayout(menu_participaLayout);
        menu_participaLayout.setHorizontalGroup(
            menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_participaLayout.createSequentialGroup()
                .addGroup(menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_participaLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(menu_participa_btn_aceptar)
                        .addGap(46, 46, 46)
                        .addComponent(menu_participa_btn_cancelar))
                    .addGroup(menu_participaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(menu_participaLayout.createSequentialGroup()
                                .addGroup(menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(menu_participa_eti_nombre_guerra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(menu_participa_eti_nombre_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(menu_participaLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(menu_participa_field_id_guerra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menu_participaLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(menu_participa_field_id_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(menu_participa_eti_fecha_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menu_participa_eti_fecha_salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menu_participa_eti_bando, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu_participa_cbox_bando, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(menu_participa_txtfield_fecha_salida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(menu_participa_txtfield_fecha_entrada, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        menu_participaLayout.setVerticalGroup(
            menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_participaLayout.createSequentialGroup()
                .addGroup(menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_participaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(menu_participa_eti_nombre_guerra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_participa_field_id_guerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menu_participa_eti_nombre_pais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_participa_field_id_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_participaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu_participa_eti_fecha_entrada)
                            .addComponent(menu_participa_txtfield_fecha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu_participa_txtfield_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_participa_eti_fecha_salida))
                        .addGap(22, 22, 22)
                        .addGroup(menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu_participa_eti_bando)
                            .addComponent(menu_participa_cbox_bando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(menu_participaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_participa_btn_aceptar)
                    .addComponent(menu_participa_btn_cancelar))
                .addGap(65, 65, 65))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grupo3 - Base de Datos \"guerras\"");
        setMinimumSize(new java.awt.Dimension(750, 675));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        btn_participa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_participa.setText("participa");
        btn_participa.setActionCommand("Listar_Participa");
        btn_participa.setPreferredSize(new java.awt.Dimension(150, 40));

        btn_paises.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_paises.setText("Países");
        btn_paises.setActionCommand("Listar_Países");
        btn_paises.setPreferredSize(new java.awt.Dimension(150, 40));

        btn_independencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_independencia.setText("periodo independencia");
        btn_independencia.setActionCommand("Listar_Independencias");
        btn_independencia.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btn_independencia.setPreferredSize(new java.awt.Dimension(150, 40));

        btn_guerras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guerras.setText("Guerras");
        btn_guerras.setActionCommand("Listar_Guerras");
        btn_guerras.setPreferredSize(new java.awt.Dimension(150, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BASE DE DATOS GUERRAS");

        javax.swing.GroupLayout NorthLayout = new javax.swing.GroupLayout(North);
        North.setLayout(NorthLayout);
        NorthLayout.setHorizontalGroup(
            NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorthLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_guerras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NorthLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(NorthLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(btn_participa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addComponent(btn_independencia, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)))
                .addComponent(btn_paises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        NorthLayout.setVerticalGroup(
            NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_paises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_independencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_participa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guerras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(North, java.awt.BorderLayout.NORTH);

        Center.setPreferredSize(new java.awt.Dimension(500, 500));
        Center.setLayout(new javax.swing.BoxLayout(Center, javax.swing.BoxLayout.LINE_AXIS));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        Center.add(jScrollPane1);

        getContentPane().add(Center, java.awt.BorderLayout.CENTER);

        mensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensaje.setText("Conectado a base de datos \"Guerra\"");

        btn_modificar_relacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_modificar_relacion.setForeground(new java.awt.Color(0, 153, 0));
        btn_modificar_relacion.setText("Modificar Relación");
        btn_modificar_relacion.setActionCommand("Modificar_Relacion");

        btn_borrar_relacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_borrar_relacion.setForeground(new java.awt.Color(255, 0, 0));
        btn_borrar_relacion.setText("Borrar Relación");
        btn_borrar_relacion.setActionCommand("Borrar_Relacion");

        javax.swing.GroupLayout SouthLayout = new javax.swing.GroupLayout(South);
        South.setLayout(SouthLayout);
        SouthLayout.setHorizontalGroup(
            SouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SouthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 1154, Short.MAX_VALUE)
                    .addGroup(SouthLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_modificar_relacion)
                        .addGap(57, 57, 57)
                        .addComponent(btn_borrar_relacion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SouthLayout.setVerticalGroup(
            SouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SouthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_borrar_relacion, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(btn_modificar_relacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(South, java.awt.BorderLayout.SOUTH);

        West.setMaximumSize(new java.awt.Dimension(500, 32767));
        West.setPreferredSize(new java.awt.Dimension(250, 500));

        panel_datos_guerra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Guerra", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panel_datos_guerra.setMinimumSize(new java.awt.Dimension(100, 180));
        panel_datos_guerra.setPreferredSize(new java.awt.Dimension(180, 180));

        eti_fecha_inicio.setText("fecha_inicio:");

        eti_fecha_fin.setText("fecha_fin:");

        eti_id_guerra.setText("id:");

        eti_nombre_guerra.setText("nombre:");

        lista_guerras.setActionCommand("Guerra_Seleccionada");
        lista_guerras.setMaximumSize(new java.awt.Dimension(160, 20));
        lista_guerras.setMinimumSize(new java.awt.Dimension(160, 20));
        lista_guerras.setPreferredSize(new java.awt.Dimension(160, 20));

        btn_borrar_guerra.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_borrar_guerra.setForeground(new java.awt.Color(153, 0, 0));
        btn_borrar_guerra.setText("x");
        btn_borrar_guerra.setActionCommand("Borrar_Guerra");
        btn_borrar_guerra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_borrar_guerra.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_borrar_guerra.setMaximumSize(new java.awt.Dimension(20, 20));
        btn_borrar_guerra.setMinimumSize(new java.awt.Dimension(20, 20));
        btn_borrar_guerra.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout panel_datos_guerraLayout = new javax.swing.GroupLayout(panel_datos_guerra);
        panel_datos_guerra.setLayout(panel_datos_guerraLayout);
        panel_datos_guerraLayout.setHorizontalGroup(
            panel_datos_guerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_guerraLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(panel_datos_guerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eti_fecha_fin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eti_fecha_inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_datos_guerraLayout.createSequentialGroup()
                        .addComponent(lista_guerras, 0, 161, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_borrar_guerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eti_id_guerra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eti_nombre_guerra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_datos_guerraLayout.setVerticalGroup(
            panel_datos_guerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_guerraLayout.createSequentialGroup()
                .addGroup(panel_datos_guerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lista_guerras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_borrar_guerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(eti_id_guerra)
                .addGap(4, 4, 4)
                .addComponent(eti_nombre_guerra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eti_fecha_inicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eti_fecha_fin)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        panel_box_paises.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir participante a tabla", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panel_box_paises.setMinimumSize(new java.awt.Dimension(180, 100));
        panel_box_paises.setPreferredSize(new java.awt.Dimension(180, 500));
        panel_box_paises.setLayout(new javax.swing.BoxLayout(panel_box_paises, javax.swing.BoxLayout.LINE_AXIS));

        lista_paises_neutrales.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lista_paises_neutrales);

        panel_box_paises.add(jScrollPane2);

        añadir_pais.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        añadir_pais.setText(">>");
        añadir_pais.setActionCommand("Añadir_Paises");
        añadir_pais.setMargin(new java.awt.Insets(2, 0, 2, 0));
        añadir_pais.setMaximumSize(new java.awt.Dimension(23, 32767));
        panel_box_paises.add(añadir_pais);

        panel_añadir_guerra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir(+) / Modificar(M) guerra", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panel_añadir_guerra.setMaximumSize(new java.awt.Dimension(180, 32767));
        panel_añadir_guerra.setMinimumSize(new java.awt.Dimension(180, 6));
        panel_añadir_guerra.setPreferredSize(new java.awt.Dimension(180, 130));

        eti_nombre_guerra2.setText("nombre:");

        eti_fecha_inicio2.setText("fecha_inicio:");

        txtfield_fecha_inicio.setText("aaaa-mm-dd");
        txtfield_fecha_inicio.setMinimumSize(new java.awt.Dimension(1, 1));

        txtfield_fecha_fin.setText("aaaa-mm-dd");
        txtfield_fecha_fin.setMinimumSize(new java.awt.Dimension(1, 1));

        eti_fecha_fin2.setText("fecha_fin:");

        btn_nueva_guerra.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_nueva_guerra.setForeground(new java.awt.Color(0, 153, 0));
        btn_nueva_guerra.setText("+");
        btn_nueva_guerra.setActionCommand("Nueva_Guerra");
        btn_nueva_guerra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nueva_guerra.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_nueva_guerra.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout panel_añadir_guerraLayout = new javax.swing.GroupLayout(panel_añadir_guerra);
        panel_añadir_guerra.setLayout(panel_añadir_guerraLayout);
        panel_añadir_guerraLayout.setHorizontalGroup(
            panel_añadir_guerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_añadir_guerraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_añadir_guerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_añadir_guerraLayout.createSequentialGroup()
                        .addComponent(eti_nombre_guerra2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_añadir_guerraLayout.createSequentialGroup()
                        .addComponent(txtfield_nombre_guerra)
                        .addGap(18, 18, 18)
                        .addComponent(btn_nueva_guerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_añadir_guerraLayout.createSequentialGroup()
                        .addGroup(panel_añadir_guerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_añadir_guerraLayout.createSequentialGroup()
                                .addComponent(txtfield_fecha_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addGroup(panel_añadir_guerraLayout.createSequentialGroup()
                                .addComponent(eti_fecha_inicio2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panel_añadir_guerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfield_fecha_fin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_añadir_guerraLayout.createSequentialGroup()
                                .addComponent(eti_fecha_fin2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panel_añadir_guerraLayout.setVerticalGroup(
            panel_añadir_guerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_añadir_guerraLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(eti_nombre_guerra2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_añadir_guerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield_nombre_guerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nueva_guerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_añadir_guerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eti_fecha_fin2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eti_fecha_inicio2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_añadir_guerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield_fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_fecha_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout WestLayout = new javax.swing.GroupLayout(West);
        West.setLayout(WestLayout);
        WestLayout.setHorizontalGroup(
            WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_box_paises, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_datos_guerra, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(panel_añadir_guerra, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap())
        );
        WestLayout.setVerticalGroup(
            WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WestLayout.createSequentialGroup()
                .addComponent(panel_datos_guerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panel_box_paises, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(panel_añadir_guerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(West, java.awt.BorderLayout.WEST);

        East.setPreferredSize(new java.awt.Dimension(250, 500));

        panel_datos_pais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "País", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panel_datos_pais.setMinimumSize(new java.awt.Dimension(100, 180));
        panel_datos_pais.setPreferredSize(new java.awt.Dimension(180, 180));

        eti_id_pais.setText("id:");

        eti_nombre_pais.setText("nombre:");

        eti_periodos_independencia.setText("periodos de independencia:");

        lista_paises.setActionCommand("Pais_Seleccionado");
        lista_paises.setMaximumSize(new java.awt.Dimension(160, 20));
        lista_paises.setMinimumSize(new java.awt.Dimension(160, 20));
        lista_paises.setPreferredSize(new java.awt.Dimension(160, 20));

        btn_borrar_pais.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_borrar_pais.setForeground(new java.awt.Color(153, 0, 0));
        btn_borrar_pais.setText("x");
        btn_borrar_pais.setActionCommand("Borrar_Pais");
        btn_borrar_pais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_borrar_pais.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_borrar_pais.setPreferredSize(new java.awt.Dimension(25, 25));

        lista_periodos_independencia.setBackground(java.awt.SystemColor.controlHighlight);
        lista_periodos_independencia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(lista_periodos_independencia);

        btn_borrar_periodo_independencia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_borrar_periodo_independencia.setForeground(new java.awt.Color(153, 0, 0));
        btn_borrar_periodo_independencia.setText("x");
        btn_borrar_periodo_independencia.setActionCommand("Borrar_Independencia");
        btn_borrar_periodo_independencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_borrar_periodo_independencia.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_borrar_periodo_independencia.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout panel_datos_paisLayout = new javax.swing.GroupLayout(panel_datos_pais);
        panel_datos_pais.setLayout(panel_datos_paisLayout);
        panel_datos_paisLayout.setHorizontalGroup(
            panel_datos_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_paisLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(panel_datos_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos_paisLayout.createSequentialGroup()
                        .addComponent(eti_nombre_pais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datos_paisLayout.createSequentialGroup()
                        .addGroup(panel_datos_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eti_periodos_independencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eti_id_pais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_datos_paisLayout.createSequentialGroup()
                                .addComponent(lista_paises, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_borrar_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4))))
            .addGroup(panel_datos_paisLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_borrar_periodo_independencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_datos_paisLayout.setVerticalGroup(
            panel_datos_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_paisLayout.createSequentialGroup()
                .addGroup(panel_datos_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lista_paises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_borrar_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(eti_id_pais)
                .addGap(4, 4, 4)
                .addComponent(eti_nombre_pais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eti_periodos_independencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_datos_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datos_paisLayout.createSequentialGroup()
                        .addComponent(btn_borrar_periodo_independencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datos_paisLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        panel_box_guerras.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir conflicto a tabla", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panel_box_guerras.setMaximumSize(new java.awt.Dimension(180, 32767));
        panel_box_guerras.setMinimumSize(new java.awt.Dimension(180, 100));
        panel_box_guerras.setPreferredSize(new java.awt.Dimension(180, 500));
        panel_box_guerras.setLayout(new javax.swing.BoxLayout(panel_box_guerras, javax.swing.BoxLayout.LINE_AXIS));

        añadir_guerra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        añadir_guerra.setText("<<");
        añadir_guerra.setActionCommand("Añadir_Guerras");
        añadir_guerra.setMargin(new java.awt.Insets(2, 0, 2, 0));
        añadir_guerra.setMaximumSize(new java.awt.Dimension(23, 32767));
        panel_box_guerras.add(añadir_guerra);

        lista_guerras_neutral.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(lista_guerras_neutral);

        panel_box_guerras.add(jScrollPane3);

        panel_añadir_pais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir(+) / Modificar(M) País", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panel_añadir_pais.setPreferredSize(new java.awt.Dimension(180, 130));

        eti_nombre_pais1.setText("nombre:");

        btn_nuevo_pais.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_nuevo_pais.setForeground(new java.awt.Color(0, 153, 0));
        btn_nuevo_pais.setText("+");
        btn_nuevo_pais.setActionCommand("Nuevo_Pais");
        btn_nuevo_pais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nuevo_pais.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_nuevo_pais.setMaximumSize(null);
        btn_nuevo_pais.setMinimumSize(null);
        btn_nuevo_pais.setPreferredSize(new java.awt.Dimension(25, 25));

        txtfield_inicio_independencia.setText("aaaa-mm-dd");
        txtfield_inicio_independencia.setPreferredSize(new java.awt.Dimension(75, 20));

        txtfield_fin_independencia.setText("aaaa-mm-dd");
        txtfield_fin_independencia.setPreferredSize(new java.awt.Dimension(75, 20));

        btn_nueva_independencia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_nueva_independencia.setForeground(new java.awt.Color(0, 153, 0));
        btn_nueva_independencia.setText("+");
        btn_nueva_independencia.setActionCommand("Nueva_Independencia");
        btn_nueva_independencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nueva_independencia.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_nueva_independencia.setPreferredSize(new java.awt.Dimension(25, 25));

        eti_periodos_independencia1.setText("periodo de independencia:");

        javax.swing.GroupLayout panel_añadir_paisLayout = new javax.swing.GroupLayout(panel_añadir_pais);
        panel_añadir_pais.setLayout(panel_añadir_paisLayout);
        panel_añadir_paisLayout.setHorizontalGroup(
            panel_añadir_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_añadir_paisLayout.createSequentialGroup()
                .addGroup(panel_añadir_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_añadir_paisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_añadir_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_añadir_paisLayout.createSequentialGroup()
                                .addComponent(txtfield_nombre_pais)
                                .addGap(18, 18, 18)
                                .addComponent(btn_nuevo_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_añadir_paisLayout.createSequentialGroup()
                                .addGroup(panel_añadir_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eti_periodos_independencia1)
                                    .addComponent(eti_nombre_pais1))
                                .addGap(0, 71, Short.MAX_VALUE))))
                    .addGroup(panel_añadir_paisLayout.createSequentialGroup()
                        .addComponent(txtfield_inicio_independencia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfield_fin_independencia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_nueva_independencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_añadir_paisLayout.setVerticalGroup(
            panel_añadir_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_añadir_paisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eti_nombre_pais1)
                .addGap(1, 1, 1)
                .addGroup(panel_añadir_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield_nombre_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nuevo_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eti_periodos_independencia1)
                .addGap(3, 3, 3)
                .addGroup(panel_añadir_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield_inicio_independencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_fin_independencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nueva_independencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EastLayout = new javax.swing.GroupLayout(East);
        East.setLayout(EastLayout);
        EastLayout.setHorizontalGroup(
            EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EastLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EastLayout.createSequentialGroup()
                        .addComponent(panel_datos_pais, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EastLayout.createSequentialGroup()
                        .addGroup(EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel_añadir_pais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(panel_box_guerras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))))
        );
        EastLayout.setVerticalGroup(
            EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EastLayout.createSequentialGroup()
                .addComponent(panel_datos_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panel_box_guerras, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(panel_añadir_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_añadir_pais.getAccessibleContext().setAccessibleName("Añadir/Modificar país");

        getContentPane().add(East, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Vista().setVisible(true);
        });
    }

    //Inicializa las menus laterales y las tabla.
    public void limpiarTabla(){
        this.tabla.setModel(new DefaultTableModel());
        this.mensaje.setText("");
        this.btn_modificar_relacion.setVisible(false);
        this.btn_borrar_relacion.setVisible(false); 
    }
    
    public void limpiarMenuGuerra(){
        lista_guerras.setSelectedIndex(0);
        lista_paises_neutrales.setModel(new DefaultListModel<>());
        this.eti_id_guerra.setText("id:");
        this.eti_nombre_guerra.setText("nombre:");
        this.eti_fecha_inicio.setText("fechia inicio:");
        this.eti_fecha_fin.setText("fecha fin:");
        this.txtfield_nombre_guerra.setText("");
        this.txtfield_fecha_inicio.setText("aaaa-mm-dd");
        this.txtfield_fecha_fin.setText("aaaa-mm-dd");
        this.btn_nueva_guerra.setText("+");
    }
    
    public void limpiarMenuPais(){
        lista_paises.setSelectedIndex(0);
            lista_guerras_neutral.setModel(new DefaultListModel<>());
            this.eti_id_pais.setText("id:");
            this.eti_nombre_pais.setText("nombre:");
            this.lista_periodos_independencia.setModel(new DefaultListModel<>());
            this.txtfield_nombre_pais.setText("");
            this.txtfield_inicio_independencia.setText("aaaa-mm-dd");
            this.txtfield_fin_independencia.setText("aaaa-mm-dd");
            this.btn_nuevo_pais.setText("+");
    }
    
    public void limpiarVista(){
        this.mensaje.setText("");
        limpiarTabla();
        limpiarMenuGuerra();
        limpiarMenuPais();       
    }
    
    public JTable getTabla() {
        return tabla;
    }

    public void setTabla(JTable tabla) {
        this.tabla = tabla;
    }
    
    public JButton getBtn_guerras() {
        return btn_guerras;
    }

    public void setBtn_guerras(JButton btn_guerras) {
        this.btn_guerras = btn_guerras;
    }

    public JButton getBtn_paises() {
        return btn_paises;
    }

    public void setBtn_paises(JButton btn_paises) {
        this.btn_paises = btn_paises;
    }

    public JButton getBtn_independencia() {
        return btn_independencia;
    }

    public void setBtn_independencia(JButton btn_independencia) {
        this.btn_independencia = btn_independencia;
    }

    public JButton getBtn_borrar_relacion() {
        return btn_borrar_relacion;
    }

    public void setBtn_borrar_relacion(JButton btn_borrar_relacion) {
        this.btn_borrar_relacion = btn_borrar_relacion;
    }

    public JButton getBtn_modificar_relacion() {
        return btn_modificar_relacion;
    }

    public void setBtn_modificar_relacion(JButton btn_modificar_relacion) {
        this.btn_modificar_relacion = btn_modificar_relacion;
    }
    
    public JButton getBtn_participa() {
        return btn_participa;
    }

    public void setBtn_participa(JButton btn_participa) {
        this.btn_participa = btn_participa;
    }
    
    public JComboBox<String> getLista_guerras() {
        return lista_guerras;
    }

    public void setLista_guerras(JComboBox<String> lista_guerras) {
        this.lista_guerras = lista_guerras;
    }

    public JComboBox<String> getLista_paises() {
        return lista_paises;
    }

    public void setLista_paises(JComboBox<String> lista_paises) {
        this.lista_paises = lista_paises;
    }

    public JList<String> getLista_guerras_neutral() {
        return lista_guerras_neutral;
    }

    public void setLista_guerras_neutral(JList<String> lista_guerras_neutral) {
        this.lista_guerras_neutral = lista_guerras_neutral;
    }

    public JList<String> getLista_paises_neutrales() {
        return lista_paises_neutrales;
    }

    public void setLista_paises_neutrales(JList<String> lista_paises_neutrales) {
        this.lista_paises_neutrales = lista_paises_neutrales;
    }

    public JList<String> getLista_periodos_independencia() {
        return lista_periodos_independencia;
    }

    public void setLista_periodos_independencia(JList<String> lista_periodos_independencia) {
        this.lista_periodos_independencia = lista_periodos_independencia;
    }

    public JButton getAñadir_guerra() {
        return añadir_guerra;
    }

    public void setAñadir_guerra(JButton añadir_guerra) {
        this.añadir_guerra = añadir_guerra;
    }

    public JButton getBtn_borrar_guerra() {
        return btn_borrar_guerra;
    }

    public void setBtn_borrar_guerra(JButton btn_borrar_guerra) {
        this.btn_borrar_guerra = btn_borrar_guerra;
    }

    public JButton getBtn_borrar_pais() {
        return btn_borrar_pais;
    }

    public void setBtn_borrar_pais(JButton btn_borrar_pais) {
        this.btn_borrar_pais = btn_borrar_pais;
    }

    public JButton getBtn_nueva_guerra() {
        return btn_nueva_guerra;
    }

    public void setBtn_nueva_guerra(JButton btn_nueva_guerra) {
        this.btn_nueva_guerra = btn_nueva_guerra;
    }

    public JButton getBtn_nueva_independencia() {
        return btn_nueva_independencia;
    }

    public void setBtn_nueva_independencia(JButton btn_nueva_independencia) {
        this.btn_nueva_independencia = btn_nueva_independencia;
    }

    public JButton getBtn_nuevo_pais() {
        return btn_nuevo_pais;
    }

    public void setBtn_nuevo_pais(JButton btn_nuevo_pais) {
        this.btn_nuevo_pais = btn_nuevo_pais;
    }
    
    public JButton getAñadir_pais() {
        return añadir_pais;
    }

    public void setAñadir_pais(JButton añadir_pais) {
        this.añadir_pais = añadir_pais;
    }

    public JButton getBtn_borrar_periodo_independencia() {
        return btn_borrar_periodo_independencia;
    }

    public void setBtn_borrar_periodo_independencia(JButton btn_borrar_periodo_independencia) {
        this.btn_borrar_periodo_independencia = btn_borrar_periodo_independencia;
    }

    public JLabel getEti_fecha_fin() {
        return eti_fecha_fin;
    }

    public void setEti_fecha_fin(JLabel eti_fecha_fin) {
        this.eti_fecha_fin = eti_fecha_fin;
    }

    public JLabel getEti_fecha_inicio() {
        return eti_fecha_inicio;
    }

    public void setEti_fecha_inicio(JLabel eti_fecha_inicio) {
        this.eti_fecha_inicio = eti_fecha_inicio;
    }

    public JLabel getEti_id_guerra() {
        return eti_id_guerra;
    }

    public void setEti_id_guerra(JLabel eti_id_guerra) {
        this.eti_id_guerra = eti_id_guerra;
    }

    public JLabel getEti_id_pais() {
        return eti_id_pais;
    }

    public void setEti_id_pais(JLabel eti_id_pais) {
        this.eti_id_pais = eti_id_pais;
    }

    public JLabel getEti_nombre_guerra() {
        return eti_nombre_guerra;
    }

    public void setEti_nombre_guerra(JLabel eti_nombre_guerra) {
        this.eti_nombre_guerra = eti_nombre_guerra;
    }

    public JLabel getEti_nombre_pais() {
        return eti_nombre_pais;
    }

    public void setEti_nombre_pais(JLabel eti_nombre_pais) {
        this.eti_nombre_pais = eti_nombre_pais;
    }

    public JTextField getTxtfield_fecha_fin() {
        return txtfield_fecha_fin;
    }

    public void setTxtfield_fecha_fin(JTextField txtfield_fecha_fin) {
        this.txtfield_fecha_fin = txtfield_fecha_fin;
    }

    public JTextField getTxtfield_fecha_inicio() {
        return txtfield_fecha_inicio;
    }

    public void setTxtfield_fecha_inicio(JTextField txtfield_fecha_inicio) {
        this.txtfield_fecha_inicio = txtfield_fecha_inicio;
    }

    public JTextField getTxtfield_inicio_independencia() {
        return txtfield_inicio_independencia;
    }

    public void setTxtfield_inicio_independencia(JTextField txtfield_inicio_independencia) {
        this.txtfield_inicio_independencia = txtfield_inicio_independencia;
    }

    public JTextField getTxtfield_nombre_guerra() {
        return txtfield_nombre_guerra;
    }

    public void setTxtfield_nombre_guerra(JTextField txtfield_nombre_guerra) {
        this.txtfield_nombre_guerra = txtfield_nombre_guerra;
    }

    public JTextField getTxtfield_nombre_pais() {
        return txtfield_nombre_pais;
    }

    public void setTxtfield_nombre_pais(JTextField txtfield_nombre_pais) {
        this.txtfield_nombre_pais = txtfield_nombre_pais;
    }

    public JTextField getTxtfield_fin_independencia() {
        return txtfield_fin_independencia;
    }

    public void setTxtfield_fin_independencia(JTextField txtfield_fin_independencia) {
        this.txtfield_fin_independencia = txtfield_fin_independencia;
    }

    public JLabel getMensaje() {
        return mensaje;
    }

    public void setMensaje(JLabel mensaje) {
        this.mensaje = mensaje;
    }

    public JDialog getMenu_participa() {
        return menu_participa;
    }

    public JButton getMenu_participa_btn_aceptar() {
        return menu_participa_btn_aceptar;
    }

    public void setMenu_participa_btn_aceptar(JButton menu_participa_btn_aceptar) {
        this.menu_participa_btn_aceptar = menu_participa_btn_aceptar;
    }

    public JButton getMenu_participa_btn_cancelar() {
        return menu_participa_btn_cancelar;
    }

    public void setMenu_participa_btn_cancelar(JButton menu_participa_btn_cancelar) {
        this.menu_participa_btn_cancelar = menu_participa_btn_cancelar;
    }

    public JComboBox<String> getMenu_participa_cbox_bando() {
        return menu_participa_cbox_bando;
    }

    public void setMenu_participa_cbox_bando(JComboBox<String> menu_participa_cbox_bando) {
        this.menu_participa_cbox_bando = menu_participa_cbox_bando;
    }

    public JLabel getMenu_participa_eti_nombre_guerra() {
        return menu_participa_eti_nombre_guerra;
    }

    public void setMenu_participa_eti_nombre_guerra(JLabel menu_participa_eti_nombre_guerra) {
        this.menu_participa_eti_nombre_guerra = menu_participa_eti_nombre_guerra;
    }

    public JLabel getMenu_participa_eti_nombre_pais() {
        return menu_participa_eti_nombre_pais;
    }

    public void setMenu_participa_eti_nombre_pais(JLabel menu_participa_eti_nombre_pais) {
        this.menu_participa_eti_nombre_pais = menu_participa_eti_nombre_pais;
    }

    public JTextField getMenu_participa_field_id_guerra() {
        return menu_participa_field_id_guerra;
    }

    public void setMenu_participa_field_id_guerra(JTextField menu_participa_field_id_guerra) {
        this.menu_participa_field_id_guerra = menu_participa_field_id_guerra;
    }

    public JTextField getMenu_participa_field_id_pais() {
        return menu_participa_field_id_pais;
    }

    public void setMenu_participa_field_id_pais(JTextField menu_participa_field_id_pais) {
        this.menu_participa_field_id_pais = menu_participa_field_id_pais;
    }

    public JTextField getMenu_participa_txtfield_fecha_entrada() {
        return menu_participa_txtfield_fecha_entrada;
    }

    public void setMenu_participa_txtfield_fecha_entrada(JTextField menu_participa_txtfield_fecha_entrada) {
        this.menu_participa_txtfield_fecha_entrada = menu_participa_txtfield_fecha_entrada;
    }

    public JTextField getMenu_participa_txtfield_fecha_salida() {
        return menu_participa_txtfield_fecha_salida;
    }

    public void setMenu_participa_txtfield_fecha_salida(JTextField menu_participa_txtfield_fecha_salida) {
        this.menu_participa_txtfield_fecha_salida = menu_participa_txtfield_fecha_salida;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Center;
    private javax.swing.JPanel East;
    private javax.swing.JPanel North;
    private javax.swing.JPanel South;
    private javax.swing.JPanel West;
    private javax.swing.JButton añadir_guerra;
    private javax.swing.JButton añadir_pais;
    private javax.swing.JButton btn_borrar_guerra;
    private javax.swing.JButton btn_borrar_pais;
    private javax.swing.JButton btn_borrar_periodo_independencia;
    private javax.swing.JButton btn_borrar_relacion;
    private javax.swing.JButton btn_guerras;
    private javax.swing.JButton btn_independencia;
    private javax.swing.JButton btn_modificar_relacion;
    private javax.swing.JButton btn_nueva_guerra;
    private javax.swing.JButton btn_nueva_independencia;
    private javax.swing.JButton btn_nuevo_pais;
    private javax.swing.JButton btn_paises;
    private javax.swing.JButton btn_participa;
    private javax.swing.JLabel eti_fecha_fin;
    private javax.swing.JLabel eti_fecha_fin2;
    private javax.swing.JLabel eti_fecha_inicio;
    private javax.swing.JLabel eti_fecha_inicio2;
    private javax.swing.JLabel eti_id_guerra;
    private javax.swing.JLabel eti_id_pais;
    private javax.swing.JLabel eti_nombre_guerra;
    private javax.swing.JLabel eti_nombre_guerra2;
    private javax.swing.JLabel eti_nombre_pais;
    private javax.swing.JLabel eti_nombre_pais1;
    private javax.swing.JLabel eti_periodos_independencia;
    private javax.swing.JLabel eti_periodos_independencia1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> lista_guerras;
    private javax.swing.JList<String> lista_guerras_neutral;
    private javax.swing.JComboBox<String> lista_paises;
    private javax.swing.JList<String> lista_paises_neutrales;
    private javax.swing.JList<String> lista_periodos_independencia;
    private javax.swing.JLabel mensaje;
    private javax.swing.JDialog menu_participa;
    private javax.swing.JButton menu_participa_btn_aceptar;
    private javax.swing.JButton menu_participa_btn_cancelar;
    private javax.swing.JComboBox<String> menu_participa_cbox_bando;
    private javax.swing.JLabel menu_participa_eti_bando;
    private javax.swing.JLabel menu_participa_eti_fecha_entrada;
    private javax.swing.JLabel menu_participa_eti_fecha_salida;
    private javax.swing.JLabel menu_participa_eti_nombre_guerra;
    private javax.swing.JLabel menu_participa_eti_nombre_pais;
    private javax.swing.JTextField menu_participa_field_id_guerra;
    private javax.swing.JTextField menu_participa_field_id_pais;
    private javax.swing.JTextField menu_participa_txtfield_fecha_entrada;
    private javax.swing.JTextField menu_participa_txtfield_fecha_salida;
    private javax.swing.JPanel panel_añadir_guerra;
    private javax.swing.JPanel panel_añadir_pais;
    private javax.swing.JPanel panel_box_guerras;
    private javax.swing.JPanel panel_box_paises;
    private javax.swing.JPanel panel_datos_guerra;
    private javax.swing.JPanel panel_datos_pais;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtfield_fecha_fin;
    private javax.swing.JTextField txtfield_fecha_inicio;
    private javax.swing.JTextField txtfield_fin_independencia;
    private javax.swing.JTextField txtfield_inicio_independencia;
    private javax.swing.JTextField txtfield_nombre_guerra;
    private javax.swing.JTextField txtfield_nombre_pais;
    // End of variables declaration//GEN-END:variables
}
